server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LorenaAceva/reto-config-service.git
        default-label: main
        search-paths:



